# Generated by Django 2.1.7 on 2019-04-24 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20190423_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseVal', models.FloatField(default=0)),
                ('expenseType', models.CharField(blank='True', choices=[('GR', 'Groceries'), ('EN', 'Entertainment'), ('OT', 'Other')], default='Works from Django', max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='expenseType',
            field=models.CharField(blank='True', default='Works from Django', max_length=60),
        ),
        migrations.AddField(
            model_name='expenseinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.UserInfo'),
        ),
    ]
