# Generated by Django 2.1.7 on 2019-04-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20190424_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanVal', models.CharField(blank='True', default='', max_length=60)),
                ('loanPeriod', models.CharField(blank='True', default='', max_length=60)),
                ('loanInterest', models.CharField(blank='True', default='', max_length=60)),
                ('loanType', models.CharField(choices=[('RD', 'Residential'), ('OT', 'Other')], default='Residential', max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='expenseType',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='loanAmount',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='loanInterest',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='loanPeriod',
        ),
        migrations.AlterField(
            model_name='expenseinfo',
            name='expenseType',
            field=models.CharField(choices=[('GR', 'Groceries'), ('EN', 'Entertainment'), ('OT', 'Other')], default='Other', max_length=60),
        ),
        migrations.AlterField(
            model_name='expenseinfo',
            name='expenseVal',
            field=models.CharField(blank='True', default='50', max_length=60),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='income',
            field=models.CharField(blank='True', default='100', max_length=60),
        ),
        migrations.AddField(
            model_name='loaninfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.UserInfo'),
        ),
    ]
