# Generated by Django 2.1.7 on 2019-04-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_auto_20190427_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenseinfo',
            old_name='user',
            new_name='e1',
        ),
        migrations.RenameField(
            model_name='loaninfo',
            old_name='user',
            new_name='l1',
        ),
        migrations.AlterField(
            model_name='expenseinfo',
            name='expenseType',
            field=models.CharField(default='Other', max_length=60),
        ),
        migrations.AlterField(
            model_name='loaninfo',
            name='loanType',
            field=models.CharField(default='Residential', max_length=60),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='income',
            field=models.CharField(default='1000', max_length=60),
        ),
    ]
